/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;


import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Owner
 */
public class ManageBooks extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
    
    //This is an implementation of TableModel that uses a Vector of Vectors to store the cell value objects.
     DefaultTableModel tablemodel;
     
     
    public ManageBooks() {
        initComponents();
        setBookDetailsToTable();
    }

    //Setting Book details to table
    private void setBookDetailsToTable(){
        try {
          
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","12345");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from book_details");
            while(rs.next()){
                int bookid=rs.getInt("book_id");
                int quantity=rs.getInt("quantity");
                String name=rs.getString("book_name");
                String author=rs.getString("author_name");
                tablemodel=(DefaultTableModel)table_bookdetails.getModel();
                Object[] table_contents={bookid,name,author,quantity};
                /*
                Adds a row to the end of the model. The new row will contain null values unless rowData
                is specified. Notification of the row being added will be generated.
                */
                tablemodel.addRow(table_contents);
            }
            
        } catch (Exception e) {
            
        }
    }
    
    //Add book to data base
    private boolean addBook(){
        boolean isAdded=false;
        try {
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","12345");
            PreparedStatement pstm=con.prepareStatement("insert into book_details values(?,?,?,?)");
            pstm.setInt(1, Integer.parseInt(txt_bookid.getText()));
            pstm.setString(2, txt_bookname.getText());
            pstm.setString(3, txt_authorname.getText());
            pstm.setInt(4, Integer.parseInt(txt_quantity.getText()));
            int rowCount=pstm.executeUpdate();
            if(rowCount>0){
                isAdded=true;
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isAdded;
    }
    //Update books details
    private boolean updateBooks(){
          try {
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","12345");
            PreparedStatement pstm=con.prepareStatement("update book_details set book_name=? , author_name=?, quantity=? where book_id=?");
            
            pstm.setString(1, txt_bookname.getText());
            pstm.setString(2, txt_authorname.getText());
            pstm.setInt(3, Integer.parseInt(txt_quantity.getText()));
            pstm.setInt(4, Integer.parseInt(txt_bookid.getText()));
            int rowCount=pstm.executeUpdate();
            if(rowCount>0){
                return true;
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
          return false;
    }
    
    //Delete Books Details from database
    private boolean deleteBooks(){
         try {
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","12345");
            PreparedStatement pstm=con.prepareStatement("delete from book_details where book_id=?");
            pstm.setInt(1, Integer.parseInt(txt_bookid.getText()));
          
            int rowCount=pstm.executeUpdate();
            if(rowCount>0){
                return true;
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
          return false;
    }
    
    //Method to clear table contenets
    private void clearTable(){
        tablemodel.setRowCount(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_bookid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_authorname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_bookname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        update_bttn = new javax.swing.JButton();
        add_bttn = new javax.swing.JButton();
        delete_bttn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        back_bttn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_bookdetails = new rojerusan.RSTableMetro();
        label_exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(54, 60, 73));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(40, 45, 55));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 110, 127));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageBookIcon/icons8-id-20.png"))); // NOI18N
        jLabel2.setText("Book Id");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 90, 30));

        txt_bookid.setBackground(new java.awt.Color(40, 45, 55));
        txt_bookid.setForeground(new java.awt.Color(106, 110, 127));
        txt_bookid.setText("Enter Book Id");
        txt_bookid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 60, 73), 1, true));
        txt_bookid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_bookidFocusGained(evt);
            }
        });
        txt_bookid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_bookidMouseClicked(evt);
            }
        });
        txt_bookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookidActionPerformed(evt);
            }
        });
        jPanel2.add(txt_bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 300, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(106, 110, 127));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageBookIcon/icons8-book-20.png"))); // NOI18N
        jLabel5.setText("Book Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 30));

        txt_authorname.setBackground(new java.awt.Color(40, 45, 55));
        txt_authorname.setForeground(new java.awt.Color(106, 110, 127));
        txt_authorname.setText("Enter Author Name");
        txt_authorname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 60, 73), 1, true));
        txt_authorname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_authornameFocusGained(evt);
            }
        });
        txt_authorname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_authornameMouseClicked(evt);
            }
        });
        txt_authorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_authornameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_authorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 300, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(106, 110, 127));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageBookIcon/icons8-writer-male-20.png"))); // NOI18N
        jLabel6.setText("Author Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 30));

        txt_bookname.setBackground(new java.awt.Color(40, 45, 55));
        txt_bookname.setForeground(new java.awt.Color(106, 110, 127));
        txt_bookname.setText("Enter Book Name");
        txt_bookname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 60, 73), 1, true));
        txt_bookname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_booknameFocusGained(evt);
            }
        });
        txt_bookname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_booknameMouseClicked(evt);
            }
        });
        txt_bookname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_booknameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 300, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(106, 110, 127));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageBookIcon/icons8-how-many-quest-20.png"))); // NOI18N
        jLabel7.setText("Quantity");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 100, 30));

        txt_quantity.setBackground(new java.awt.Color(40, 45, 55));
        txt_quantity.setForeground(new java.awt.Color(106, 110, 127));
        txt_quantity.setText("Enter Quantity");
        txt_quantity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 60, 73), 1, true));
        txt_quantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_quantityFocusGained(evt);
            }
        });
        txt_quantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_quantityMouseClicked(evt);
            }
        });
        txt_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantityActionPerformed(evt);
            }
        });
        jPanel2.add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 300, 30));

        update_bttn.setBackground(new java.awt.Color(40, 45, 55));
        update_bttn.setForeground(new java.awt.Color(106, 110, 127));
        update_bttn.setText("Update");
        update_bttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 110, 127)));
        update_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_bttnActionPerformed(evt);
            }
        });
        jPanel2.add(update_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 110, 30));

        add_bttn.setBackground(new java.awt.Color(40, 45, 55));
        add_bttn.setForeground(new java.awt.Color(106, 110, 127));
        add_bttn.setText("Add");
        add_bttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 110, 127)));
        add_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bttnActionPerformed(evt);
            }
        });
        jPanel2.add(add_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 110, 30));

        delete_bttn.setBackground(new java.awt.Color(40, 45, 55));
        delete_bttn.setForeground(new java.awt.Color(106, 110, 127));
        delete_bttn.setText("Delete");
        delete_bttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 110, 127)));
        delete_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_bttnActionPerformed(evt);
            }
        });
        jPanel2.add(delete_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 110, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 420, 480));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 110, 127));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageBookIcon/icons8-book-60.png"))); // NOI18N
        jLabel3.setText("    Manage Books");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 280, -1));

        back_bttn.setBackground(new java.awt.Color(40, 45, 55));
        back_bttn.setForeground(new java.awt.Color(106, 110, 127));
        back_bttn.setText("Back");
        back_bttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 110, 127)));
        back_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_bttnActionPerformed(evt);
            }
        });
        jPanel1.add(back_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 110, 30));

        table_bookdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Book Name ", "Author Name", "Quantity"
            }
        ));
        table_bookdetails.setColorBackgoundHead(new java.awt.Color(40, 45, 55));
        table_bookdetails.setColorBordeFilas(new java.awt.Color(54, 60, 73));
        table_bookdetails.setColorBordeHead(new java.awt.Color(54, 60, 73));
        table_bookdetails.setColorFilasBackgound1(new java.awt.Color(40, 45, 55));
        table_bookdetails.setColorFilasBackgound2(new java.awt.Color(40, 45, 55));
        table_bookdetails.setColorForegroundHead(new java.awt.Color(106, 110, 127));
        table_bookdetails.setRowHeight(62);
        table_bookdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_bookdetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_bookdetails);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 1040, 480));

        label_exit.setBackground(new java.awt.Color(54, 60, 73));
        label_exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        label_exit.setForeground(new java.awt.Color(255, 255, 255));
        label_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_exit.setText("X");
        label_exit.setOpaque(true);
        label_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_exitMouseExited(evt);
            }
        });
        jPanel1.add(label_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 0, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1500, 700));

        setSize(new java.awt.Dimension(1500, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void back_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_bttnActionPerformed
       HomePage home=new HomePage();
       home.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_back_bttnActionPerformed

    private void delete_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_bttnActionPerformed
     if(deleteBooks()==true){
            JOptionPane.showMessageDialog(this, "Book Deleted");
 
            //clear table contenets first before setBookDetailsToTable() to avoid duplicacy
            clearTable();
            setBookDetailsToTable();
        }
        else{
             JOptionPane.showMessageDialog(this, "failed To Delete");
             
        }
    }//GEN-LAST:event_delete_bttnActionPerformed

    private void add_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bttnActionPerformed
        if(addBook()==true){
            JOptionPane.showMessageDialog(this, "Book Added");
 
            //clear table contenets first before setBookDetailsToTable() to avoid duplicacy
            clearTable();
            setBookDetailsToTable();
        }
        else{
             JOptionPane.showMessageDialog(this, "failed to Add");
             
        }
    }//GEN-LAST:event_add_bttnActionPerformed

    private void update_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_bttnActionPerformed
       if(updateBooks()==true){
           JOptionPane.showMessageDialog(this, "Book Updated");
           clearTable();
           setBookDetailsToTable();
       }
       else{
           JOptionPane.showMessageDialog(this, "Failed to Update");
       }
    }//GEN-LAST:event_update_bttnActionPerformed

    private void txt_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantityActionPerformed

    private void txt_quantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_quantityMouseClicked
        if(txt_quantity.getText().equals("Enter Quantity")){
            txt_quantity.setText("");
        }
    }//GEN-LAST:event_txt_quantityMouseClicked

    private void txt_quantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_quantityFocusGained
        if(txt_quantity.getText().equals("Enter Quantity")){
            txt_quantity.setText("");
        }
    }//GEN-LAST:event_txt_quantityFocusGained

    private void txt_booknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_booknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_booknameActionPerformed

    private void txt_booknameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_booknameMouseClicked
    if(txt_bookname.getText().equals("Enter Book Name")){
            txt_bookname.setText("");
        }
    }//GEN-LAST:event_txt_booknameMouseClicked

    private void txt_booknameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_booknameFocusGained
        if(txt_bookname.getText().equals("Enter Book Name")){
            txt_bookname.setText("");
        }
    }//GEN-LAST:event_txt_booknameFocusGained

    private void txt_authornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_authornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_authornameActionPerformed

    private void txt_authornameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_authornameMouseClicked
        if(txt_authorname.getText().equals("Enter Author Name")){
            txt_authorname.setText("");
        }
    }//GEN-LAST:event_txt_authornameMouseClicked

    private void txt_authornameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_authornameFocusGained
        if(txt_authorname.getText().equals("Enter Author Name")){
            txt_authorname.setText("");
        }
    }//GEN-LAST:event_txt_authornameFocusGained

    private void txt_bookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookidActionPerformed

    private void txt_bookidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_bookidMouseClicked

    }//GEN-LAST:event_txt_bookidMouseClicked

    private void txt_bookidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookidFocusGained
        if(txt_bookid.getText().equals("Enter Book Id")){
            txt_bookid.setText("");
        }
    }//GEN-LAST:event_txt_bookidFocusGained

    private void table_bookdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_bookdetailsMouseClicked
       TableModel tmodel=table_bookdetails.getModel();
        /*
        The TableModel interface specifies the methods the JTable will use to interrogate a tabular data model.
The JTable can be set up to display any data model which implements the TableModel interface with a couple of lines of code:
        */
      
        int rowNo=table_bookdetails.getSelectedRow();
        txt_bookid.setText(tmodel.getValueAt(rowNo, 0).toString());
        txt_bookname.setText(tmodel.getValueAt(rowNo, 1).toString());
        txt_authorname.setText(tmodel.getValueAt(rowNo, 2).toString());
        txt_quantity.setText(tmodel.getValueAt(rowNo, 3).toString());
    }//GEN-LAST:event_table_bookdetailsMouseClicked

    private void label_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_label_exitMouseClicked

    private void label_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseEntered
        label_exit.setBackground(Color.red);
    }//GEN-LAST:event_label_exitMouseEntered

    private void label_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseExited
        label_exit.setBackground(new Color(54,60,73));
    }//GEN-LAST:event_label_exitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_bttn;
    private javax.swing.JButton back_bttn;
    private javax.swing.JButton delete_bttn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_exit;
    private rojerusan.RSTableMetro table_bookdetails;
    private javax.swing.JTextField txt_authorname;
    private javax.swing.JTextField txt_bookid;
    private javax.swing.JTextField txt_bookname;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JButton update_bttn;
    // End of variables declaration//GEN-END:variables
}
