/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;


import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Owner
 */
public class ManageStudents extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
    
    //This is an implementation of TableModel that uses a Vector of Vectors to store the cell value objects.
     DefaultTableModel tablemodel;
     
     
    public ManageStudents() {
        initComponents();
        setStudentDetailsToTable();
    }

    //Setting Book details to table
    public void setStudentDetailsToTable(){
        try {
          
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","12345");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from student_details");
            while(rs.next()){
                int studentid=rs.getInt("student_id");
                String name=rs.getString("name");
                String course=rs.getString("course");
                String branch=rs.getString("branch");
                tablemodel=(DefaultTableModel)table_Studentdetails.getModel();
                Object[] table_contents={studentid,name,course,branch};
                /*
                Adds a row to the end of the model. The new row will contain null values unless rowData
                is specified. Notification of the row being added will be generated.
                */
                tablemodel.addRow(table_contents);
            }
            
        } catch (Exception e) {
            
        }
    }
    
    //Add book to data base
    private boolean addStudent(){
        boolean isAdded=false;
        try {
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","12345");
            PreparedStatement pstm=con.prepareStatement("insert into student_details values(?,?,?,?)");
            pstm.setInt(1, Integer.parseInt(txt_studentId.getText()));
            pstm.setString(2, txt_studentName.getText());
            pstm.setString(3, combo_courseName.getSelectedItem().toString());
            pstm.setString(4, combo_branchName.getSelectedItem().toString());
            int rowCount=pstm.executeUpdate();
            if(rowCount>0){
                isAdded=true;
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isAdded;
    }
    //Update books details
    private boolean updateStudent(){
          try {
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","12345");
            PreparedStatement pstm=con.prepareStatement("update student_details set name=? , course=?, branch=? where student_id=?");
            
            pstm.setString(1, txt_studentName.getText());
            pstm.setString(2, combo_courseName.getSelectedItem().toString());
            pstm.setString(3, combo_branchName.getSelectedItem().toString());
            pstm.setInt(4, Integer.parseInt(txt_studentId.getText()));
            int rowCount=pstm.executeUpdate();
            if(rowCount>0){
                return true;
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
          return false;
    }
    
    //Delete Books Details from database
    private boolean deleteStudents(){
         try {
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","12345");
            PreparedStatement pstm=con.prepareStatement("delete from student_details where student_id=?");
            pstm.setInt(1, Integer.parseInt(txt_studentId.getText()));
          
            int rowCount=pstm.executeUpdate();
            if(rowCount>0){
                return true;
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
          return false;
    }
    
    //Method to clear table contenets
    private void clearTable(){
        tablemodel.setRowCount(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_studentId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_studentName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        update_bttn = new javax.swing.JButton();
        add_bttn = new javax.swing.JButton();
        delete_bttn = new javax.swing.JButton();
        combo_branchName = new javax.swing.JComboBox<>();
        combo_courseName = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        back_bttn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Studentdetails = new rojerusan.RSTableMetro();
        label_exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(54, 60, 73));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(40, 45, 55));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 110, 127));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageBookIcon/icons8-id-20.png"))); // NOI18N
        jLabel2.setText("Student Id");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 30));

        txt_studentId.setBackground(new java.awt.Color(40, 45, 55));
        txt_studentId.setForeground(new java.awt.Color(106, 110, 127));
        txt_studentId.setText("Enter Student Id");
        txt_studentId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 60, 73), 1, true));
        txt_studentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_studentIdFocusGained(evt);
            }
        });
        txt_studentId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_studentIdMouseClicked(evt);
            }
        });
        txt_studentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentIdActionPerformed(evt);
            }
        });
        jPanel2.add(txt_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 300, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(106, 110, 127));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageStudentIcon/icons8-name-20.png"))); // NOI18N
        jLabel5.setText("Student Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(106, 110, 127));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageStudentIcon/icons8-course-20.png"))); // NOI18N
        jLabel6.setText("Select Course");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 30));

        txt_studentName.setBackground(new java.awt.Color(40, 45, 55));
        txt_studentName.setForeground(new java.awt.Color(106, 110, 127));
        txt_studentName.setText("Enter Student Name");
        txt_studentName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 60, 73), 1, true));
        txt_studentName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_studentNameFocusGained(evt);
            }
        });
        txt_studentName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_studentNameMouseClicked(evt);
            }
        });
        txt_studentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentNameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 300, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(106, 110, 127));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageStudentIcon/icons8-branching-arrows-20.png"))); // NOI18N
        jLabel7.setText("Select Branch");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, 30));

        update_bttn.setBackground(new java.awt.Color(40, 45, 55));
        update_bttn.setForeground(new java.awt.Color(106, 110, 127));
        update_bttn.setText("Update");
        update_bttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 110, 127)));
        update_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_bttnActionPerformed(evt);
            }
        });
        jPanel2.add(update_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 110, 30));

        add_bttn.setBackground(new java.awt.Color(40, 45, 55));
        add_bttn.setForeground(new java.awt.Color(106, 110, 127));
        add_bttn.setText("Add");
        add_bttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 110, 127)));
        add_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bttnActionPerformed(evt);
            }
        });
        jPanel2.add(add_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 110, 30));

        delete_bttn.setBackground(new java.awt.Color(40, 45, 55));
        delete_bttn.setForeground(new java.awt.Color(106, 110, 127));
        delete_bttn.setText("Delete");
        delete_bttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 110, 127)));
        delete_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_bttnActionPerformed(evt);
            }
        });
        jPanel2.add(delete_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 110, 30));

        combo_branchName.setBackground(new java.awt.Color(40, 45, 55));
        combo_branchName.setForeground(new java.awt.Color(106, 110, 127));
        combo_branchName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "IT", "ECE", "EE", "MECH", "CIVIL", " " }));
        combo_branchName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 60, 73), 1, true));
        jPanel2.add(combo_branchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 300, 30));

        combo_courseName.setBackground(new java.awt.Color(40, 45, 55));
        combo_courseName.setForeground(new java.awt.Color(106, 110, 127));
        combo_courseName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BTECH", "MTECH", "DIPLOMA", " " }));
        combo_courseName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 60, 73), 1, true));
        combo_courseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_courseNameActionPerformed(evt);
            }
        });
        jPanel2.add(combo_courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 300, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 420, 480));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 110, 127));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageStudentIcon/icons8-student-60.png"))); // NOI18N
        jLabel3.setText("    Manage Students");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 320, -1));

        back_bttn.setBackground(new java.awt.Color(40, 45, 55));
        back_bttn.setForeground(new java.awt.Color(106, 110, 127));
        back_bttn.setText("Back");
        back_bttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 110, 127)));
        back_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_bttnActionPerformed(evt);
            }
        });
        jPanel1.add(back_bttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 110, 30));

        table_Studentdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", " Name ", "Course", "Branch"
            }
        ));
        table_Studentdetails.setColorBackgoundHead(new java.awt.Color(40, 45, 55));
        table_Studentdetails.setColorBordeFilas(new java.awt.Color(54, 60, 73));
        table_Studentdetails.setColorBordeHead(new java.awt.Color(54, 60, 73));
        table_Studentdetails.setColorFilasBackgound1(new java.awt.Color(40, 45, 55));
        table_Studentdetails.setColorFilasBackgound2(new java.awt.Color(40, 45, 55));
        table_Studentdetails.setColorForegroundHead(new java.awt.Color(106, 110, 127));
        table_Studentdetails.setRowHeight(62);
        table_Studentdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_StudentdetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_Studentdetails);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 1040, 480));

        label_exit.setBackground(new java.awt.Color(54, 60, 73));
        label_exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        label_exit.setForeground(new java.awt.Color(255, 255, 255));
        label_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_exit.setText("X");
        label_exit.setOpaque(true);
        label_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_exitMouseExited(evt);
            }
        });
        jPanel1.add(label_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 0, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1500, 700));

        setSize(new java.awt.Dimension(1500, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void back_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_bttnActionPerformed
       HomePage home=new HomePage();
       home.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_back_bttnActionPerformed

    private void delete_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_bttnActionPerformed
     if(deleteStudents()==true){
            JOptionPane.showMessageDialog(this, "Student Deleted");
 
            //clear table contenets first before setStudentDetailsToTable() to avoid duplicacy
            clearTable();
            setStudentDetailsToTable();
        }
        else{
             JOptionPane.showMessageDialog(this, "failed To Delete");
             
        }
    }//GEN-LAST:event_delete_bttnActionPerformed

    private void add_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bttnActionPerformed
        if(addStudent()==true){
            JOptionPane.showMessageDialog(this, "Student Added");
 
            //clear table contenets first before setStudentDetailsToTable() to avoid duplicacy
            clearTable();
            setStudentDetailsToTable();
        }
        else{
             JOptionPane.showMessageDialog(this, "failed to Add");
             
        }
    }//GEN-LAST:event_add_bttnActionPerformed

    private void update_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_bttnActionPerformed
       if(updateStudent()==true){
           JOptionPane.showMessageDialog(this, "Student Updated");
           clearTable();
           setStudentDetailsToTable();
       }
       else{
           JOptionPane.showMessageDialog(this, "Failed to Update");
       }
    }//GEN-LAST:event_update_bttnActionPerformed

    private void txt_studentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentNameActionPerformed

    private void txt_studentNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_studentNameMouseClicked
    if(txt_studentName.getText().equals("Enter Book Name")){
            txt_studentName.setText("");
        }
    }//GEN-LAST:event_txt_studentNameMouseClicked

    private void txt_studentNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentNameFocusGained
        if(txt_studentName.getText().equals("Enter Student Name")){
            txt_studentName.setText("");
        }
    }//GEN-LAST:event_txt_studentNameFocusGained

    private void txt_studentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentIdActionPerformed

    private void txt_studentIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_studentIdMouseClicked

    }//GEN-LAST:event_txt_studentIdMouseClicked

    private void txt_studentIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentIdFocusGained
        if(txt_studentId.getText().equals("Enter Student Id")){
            txt_studentId.setText("");
        }
    }//GEN-LAST:event_txt_studentIdFocusGained

    private void table_StudentdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_StudentdetailsMouseClicked
       TableModel tmodel=table_Studentdetails.getModel();
        /*
        The TableModel interface specifies the methods the JTable will use to interrogate a tabular data model.
The JTable can be set up to display any data model which implements the TableModel interface with a couple of lines of code:
        */
      
        int rowNo=table_Studentdetails.getSelectedRow();
        txt_studentId.setText(tmodel.getValueAt(rowNo, 0).toString());
        txt_studentName.setText(tmodel.getValueAt(rowNo, 1).toString());
        combo_courseName.setSelectedItem(tmodel.getValueAt(rowNo, 2).toString());
        combo_branchName.setSelectedItem(tmodel.getValueAt(rowNo, 3).toString());
    }//GEN-LAST:event_table_StudentdetailsMouseClicked

    private void combo_courseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_courseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_courseNameActionPerformed

    private void label_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_label_exitMouseClicked

    private void label_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseEntered
        label_exit.setBackground(Color.red);
    }//GEN-LAST:event_label_exitMouseEntered

    private void label_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseExited
        label_exit.setBackground(new Color(54,60,73));
    }//GEN-LAST:event_label_exitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_bttn;
    private javax.swing.JButton back_bttn;
    private javax.swing.JComboBox<String> combo_branchName;
    private javax.swing.JComboBox<String> combo_courseName;
    private javax.swing.JButton delete_bttn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_exit;
    private rojerusan.RSTableMetro table_Studentdetails;
    private javax.swing.JTextField txt_studentId;
    private javax.swing.JTextField txt_studentName;
    private javax.swing.JButton update_bttn;
    // End of variables declaration//GEN-END:variables
}
