/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Owner
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        initComponents();
    }
     //Update book count after issuing corresponding book and update the display label_quantity count
   
    
    //Fetch issued_book details from database and display into issued book details panel
    private void getIssuedBookDetails(){
        try{
      
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","12345");
        PreparedStatement pstm=con.prepareStatement("select * from issued_book where book_id=? and student_id=? and status=?");
        pstm.setInt(1, Integer.parseInt(txt_bookId.getText()));
        pstm.setInt(2, Integer.parseInt(txt_studentId.getText()));
        pstm.setString(3, "pending");
        ResultSet rs=pstm.executeQuery();
        if(rs.next()){
            label_issueId.setText(rs.getString("id"));
            label_bookName.setText(rs.getString("book_name"));
            label_studentName.setText(rs.getString("student_name"));
            label_issueDate.setText(rs.getString("issue_date"));
            label_dueDate.setText(rs.getString("due_date"));
        }
        else{
            JOptionPane.showMessageDialog(this, "Record not found");
            label_issueId.setText("");
            label_bookName.setText("");
            label_studentName.setText("");
            label_issueDate.setText("");
            label_dueDate.setText("");
        }
    }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    //method to return book
    private boolean returnBook(){
       Long l= System.currentTimeMillis();
        Date todayDate=new Date(l);
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","12345");
        PreparedStatement pstm=con.prepareStatement("update issued_book set status=?, return_date=? where book_id=? and student_id=? and status=?");
        pstm.setString(1, "returned");
        pstm.setDate(2, todayDate);
        pstm.setInt(3, Integer.parseInt(txt_bookId.getText()));
        pstm.setInt(4, Integer.parseInt(txt_studentId.getText()));
        pstm.setString(5, "pending");
        int rowCount=pstm.executeUpdate();
        if(rowCount>0){
            return true;
        }
        } catch (Exception e) {
        }
        return false;
    }
    //Update book count after returned corresponding book .
    private void updateBookCount(){
        int book_id=Integer.parseInt(txt_bookId.getText());
         try {
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","12345");
            PreparedStatement pstm=con.prepareStatement("update book_details set quantity=quantity+1 where book_id=?");
            pstm.setInt(1, book_id);
            int rowCount=pstm.executeUpdate();
            if(rowCount>0){
                JOptionPane.showMessageDialog(this, "Book count updated");
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Book count updation failed");
            }
            } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        panel_bookDetails = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_bookDetails = new javax.swing.JLabel();
        label_issueDate = new javax.swing.JLabel();
        label_issueId = new javax.swing.JLabel();
        label_bookName = new javax.swing.JLabel();
        label_studentName = new javax.swing.JLabel();
        label_dueDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        label_exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_bookId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_studentId = new javax.swing.JTextField();
        bttn_returnBook = new javax.swing.JButton();
        label_bookDetails1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bttn_search = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main.setBackground(new java.awt.Color(54, 60, 73));
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_bookDetails.setBackground(new java.awt.Color(40, 45, 55));
        panel_bookDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 110, 127));
        jLabel1.setText("Issue Id");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel_bookDetails.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 60, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 110, 127));
        jLabel2.setText("Book Name");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel_bookDetails.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 110, 127));
        jLabel3.setText("Student Name");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel_bookDetails.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(106, 110, 127));
        jLabel4.setText("Issue date");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel_bookDetails.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 80, 30));

        label_bookDetails.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_bookDetails.setForeground(new java.awt.Color(106, 110, 127));
        label_bookDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageBookIcon/icons8-book-60.png"))); // NOI18N
        label_bookDetails.setText("  Issued  Book Details");
        panel_bookDetails.add(label_bookDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 310, -1));

        label_issueDate.setBackground(new java.awt.Color(40, 45, 55));
        label_issueDate.setForeground(new java.awt.Color(106, 110, 127));
        label_issueDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(54, 60, 73)));
        panel_bookDetails.add(label_issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 295, 30));

        label_issueId.setBackground(new java.awt.Color(40, 45, 55));
        label_issueId.setForeground(new java.awt.Color(106, 110, 127));
        label_issueId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(54, 60, 73)));
        panel_bookDetails.add(label_issueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 295, 30));

        label_bookName.setBackground(new java.awt.Color(40, 45, 55));
        label_bookName.setForeground(new java.awt.Color(106, 110, 127));
        label_bookName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(54, 60, 73)));
        panel_bookDetails.add(label_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 295, 30));

        label_studentName.setBackground(new java.awt.Color(40, 45, 55));
        label_studentName.setForeground(new java.awt.Color(106, 110, 127));
        label_studentName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(54, 60, 73)));
        panel_bookDetails.add(label_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 295, 30));

        label_dueDate.setBackground(new java.awt.Color(40, 45, 55));
        label_dueDate.setForeground(new java.awt.Color(106, 110, 127));
        label_dueDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(54, 60, 73)));
        panel_bookDetails.add(label_dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 295, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(106, 110, 127));
        jLabel6.setText("Due Date");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panel_bookDetails.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 70, 30));

        panel_main.add(panel_bookDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 420, 600));

        jLabel13.setBackground(new java.awt.Color(40, 45, 55));
        jLabel13.setForeground(new java.awt.Color(106, 110, 127));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Back");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 110, 127)));
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        panel_main.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 110, 30));

        label_exit.setBackground(new java.awt.Color(54, 60, 73));
        label_exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        label_exit.setForeground(new java.awt.Color(255, 255, 255));
        label_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_exit.setText("X");
        label_exit.setOpaque(true);
        label_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_exitMouseExited(evt);
            }
        });
        panel_main.add(label_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, 50, 30));

        jPanel2.setBackground(new java.awt.Color(40, 45, 55));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_bookId.setBackground(new java.awt.Color(40, 45, 55));
        txt_bookId.setForeground(new java.awt.Color(106, 110, 127));
        txt_bookId.setText("Enter Book Id");
        txt_bookId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 60, 73), 1, true));
        txt_bookId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_bookIdFocusGained(evt);
            }
        });
        jPanel2.add(txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 320, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(106, 110, 127));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageStudentIcon/icons8-name-20.png"))); // NOI18N
        jLabel10.setText("Student Id");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 150, 30));

        txt_studentId.setBackground(new java.awt.Color(40, 45, 55));
        txt_studentId.setForeground(new java.awt.Color(106, 110, 127));
        txt_studentId.setText("Enter Student Id");
        txt_studentId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(54, 60, 73), 1, true));
        txt_studentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_studentIdFocusGained(evt);
            }
        });
        jPanel2.add(txt_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 320, 30));

        bttn_returnBook.setBackground(new java.awt.Color(40, 45, 55));
        bttn_returnBook.setForeground(new java.awt.Color(106, 110, 127));
        bttn_returnBook.setText("Return Book");
        bttn_returnBook.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 110, 127)));
        bttn_returnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_returnBookActionPerformed(evt);
            }
        });
        jPanel2.add(bttn_returnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 110, 30));

        label_bookDetails1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_bookDetails1.setForeground(new java.awt.Color(106, 110, 127));
        label_bookDetails1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageStudentIcon/icons8-student-60.png"))); // NOI18N
        label_bookDetails1.setText("Return Book");
        jPanel2.add(label_bookDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 280, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(106, 110, 127));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageBookIcon/icons8-id-20.png"))); // NOI18N
        jLabel14.setText("Book Id");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 120, 30));

        bttn_search.setBackground(new java.awt.Color(40, 45, 55));
        bttn_search.setForeground(new java.awt.Color(106, 110, 127));
        bttn_search.setText("Search");
        bttn_search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 110, 127)));
        bttn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_searchActionPerformed(evt);
            }
        });
        jPanel2.add(bttn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 110, 30));

        panel_main.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 420, 600));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/book1.png"))); // NOI18N
        panel_main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, 400, 480));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 700));

        setSize(new java.awt.Dimension(1338, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
          HomePage home=new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void label_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_label_exitMouseClicked

    private void bttn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_searchActionPerformed
       getIssuedBookDetails();
    }//GEN-LAST:event_bttn_searchActionPerformed

    private void bttn_returnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_returnBookActionPerformed
     if(returnBook() == true){
         JOptionPane.showMessageDialog(this, "Book returned successfully");
         updateBookCount();
     }
     else{
         JOptionPane.showMessageDialog(this, "Book returned failed"); 
     }
    }//GEN-LAST:event_bttn_returnBookActionPerformed

    private void txt_bookIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookIdFocusGained
            if(txt_bookId.getText().equals("Enter Book Id")){
            txt_bookId.setText("");
        }
    }//GEN-LAST:event_txt_bookIdFocusGained

    private void txt_studentIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentIdFocusGained
        if(txt_studentId.getText().equals("Enter Student Id")){
            txt_studentId.setText("");
        }
    }//GEN-LAST:event_txt_studentIdFocusGained

    private void label_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseEntered
       label_exit.setBackground(Color.red);
    }//GEN-LAST:event_label_exitMouseEntered

    private void label_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseExited
        label_exit.setBackground(new Color(54,60,73));
    }//GEN-LAST:event_label_exitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_returnBook;
    private javax.swing.JButton bttn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_bookDetails;
    private javax.swing.JLabel label_bookDetails1;
    private javax.swing.JLabel label_bookName;
    private javax.swing.JLabel label_dueDate;
    private javax.swing.JLabel label_exit;
    private javax.swing.JLabel label_issueDate;
    private javax.swing.JLabel label_issueId;
    private javax.swing.JLabel label_studentName;
    private javax.swing.JPanel panel_bookDetails;
    private javax.swing.JPanel panel_main;
    private javax.swing.JTextField txt_bookId;
    private javax.swing.JTextField txt_studentId;
    // End of variables declaration//GEN-END:variables
}
