/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class SignUp_Page extends javax.swing.JFrame {

    /**
     * Creates new form SignUp_Page
     */
    public SignUp_Page() {
        initComponents();
        
    }
    
    //Method to insert values into user table.
    public void insertSignUpDetails() throws ClassNotFoundException, SQLException{
        
        Connection con=ConnectionProvider.createConnection();
        String name=txt_username.getText();
        String email=txt_email.getText();
        String contact=txt_contact.getText();
        String query="insert into users(name,password,email,contact) values(?,?,?,?)";
        PreparedStatement pstm=con.prepareStatement(query);
        pstm.setString(1, name);
        pstm.setString(2,new String(pass_password.getPassword()));
        pstm.setString(3, email);
        pstm.setString(4, contact);
        //execute query
       int result= pstm.executeUpdate();
       if(result >0){
           JOptionPane.showMessageDialog(this, "Users added successfully");
           SignIn_Page signin=new SignIn_Page();
           signin.setVisible(true);
           this.dispose();
       }
       else{
           JOptionPane.showMessageDialog(this, "Faild to add user", "Error", JOptionPane.ERROR_MESSAGE);
       }
        
    }
    //Validation 
    public boolean signupValidation(){
         String name=txt_username.getText();
        String email=txt_email.getText();
        String contact=txt_contact.getText();
        char[] password=pass_password.getPassword();
        if(name.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter name");
            return false;
        }
        
        if(email.equals("") ){
            JOptionPane.showMessageDialog(this, "Please enter email");
            return false;
        }
         if(! email.matches("^.+@.+\\..+$")){
              JOptionPane.showMessageDialog(this, "Please enter valid email");
            return false;
        }
        
        if(contact.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter contact number");
            return false;
        }
        if(contact.length() != 10){
              JOptionPane.showMessageDialog(this, "Please enter 10 digit number");
            return false; 
        }
        
        if(password.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter password");
            return false;
        }
        
        
        
        return true;
    }
    //Duplicacy user check
    public boolean checkDuplicateUser() throws ClassNotFoundException, SQLException{
        boolean isExist=false;
         String name=txt_username.getText();
         Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","12345");
        PreparedStatement pstm=con.prepareStatement("select * from users where name=?");
        pstm.setString(1, name);
        ResultSet rs=pstm.executeQuery();
        if(rs.next()){
            isExist=true;
            
        }
        
        return isExist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bttn_signUp = new javax.swing.JButton();
        bttn_signIn = new javax.swing.JButton();
        txt_contact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pass_password = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(244, 223, 78));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/username.png"))); // NOI18N
        jLabel5.setText("Username");
        jLabel5.setIconTextGap(10);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 30));

        bttn_signUp.setBackground(new java.awt.Color(51, 204, 255));
        bttn_signUp.setText("Sign Up");
        bttn_signUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        bttn_signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_signUpActionPerformed(evt);
            }
        });
        jPanel2.add(bttn_signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 240, 30));

        bttn_signIn.setBackground(new java.awt.Color(244, 223, 78));
        bttn_signIn.setText("Sign In");
        bttn_signIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        bttn_signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_signInActionPerformed(evt);
            }
        });
        jPanel2.add(bttn_signIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 240, 30));

        txt_contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        txt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactActionPerformed(evt);
            }
        });
        jPanel2.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 240, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/email.png"))); // NOI18N
        jLabel7.setText("Email");
        jLabel7.setIconTextGap(10);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 80, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/username.png"))); // NOI18N
        jLabel8.setText("Pasword");
        jLabel8.setIconTextGap(10);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 80, 30));

        pass_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        pass_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_passwordFocusGained(evt);
            }
        });
        pass_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_passwordActionPerformed(evt);
            }
        });
        jPanel2.add(pass_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 240, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/contact.png"))); // NOI18N
        jLabel9.setText("Contact");
        jLabel9.setIconTextGap(10);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 80, 30));

        txt_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 240, 30));

        txt_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailFocusGained(evt);
            }
        });
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 240, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Sign Up");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 80, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 420, 560));

        jPanel3.setBackground(new java.awt.Color(148, 147, 152));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin icon/taxi-librarian.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 280, 270));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 560));

        setSize(new java.awt.Dimension(835, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    private void bttn_signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_signUpActionPerformed
        try {
            // Calling sign up button
            if(signupValidation() == true){
                if(checkDuplicateUser() ==false){
            insertSignUpDetails();
                }
                else
                    JOptionPane.showMessageDialog(this, "Name already exist");
            }
        } catch (Exception ex) {
           ex.printStackTrace();
        } 
    }//GEN-LAST:event_bttn_signUpActionPerformed

    private void bttn_signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_signInActionPerformed
        SignIn_Page signpage=new SignIn_Page();
        signpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttn_signInActionPerformed

    private void pass_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_passwordActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        
    }//GEN-LAST:event_txt_usernameFocusLost

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
       
    }//GEN-LAST:event_txt_usernameFocusGained

    private void pass_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_passwordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_passwordFocusGained

    private void txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusGained
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_txt_emailFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_signIn;
    private javax.swing.JButton bttn_signUp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField pass_password;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
