/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;


import javax.swing.JOptionPane;
import java.sql.*;



/**
 *
 * @author Owner
 */
public class SignIn_Page extends javax.swing.JFrame {

    /**
     * Creates new form SignUp_Page
     */
    public SignIn_Page() {
        initComponents();
                                                 
    
    }

    //Log in Validation 
    public boolean loginValidation(){
//        String name=txt_username.getText();
//        char[] pwd=txt_pwd.getPassword();
////        String password=Arrays.toString(pwd);
        if(txt_username.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Name cannot be empty");
            return false;
        }
        if(txt_pwd.getPassword().length==0){
          JOptionPane.showMessageDialog(this, "Password cannot be empty");  
          return false;
        }
        return true;
    }
    
    //credtential validation
    public void credValidation() throws ClassNotFoundException, SQLException{
            String name=txt_username.getText();
        char[] pwd=txt_pwd.getPassword();
                String password=new String(pwd);
                System.out.println(password);
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","12345");
        PreparedStatement pstm=con.prepareStatement(" select * from users where name=? and password=?");
        pstm.setString(1, name);
        pstm.setString(2, password);
        ResultSet set=pstm.executeQuery();
        if(set.next()){
            HomePage homepage=new HomePage();
            homepage.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Incorrect username or password");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        signupbttn = new javax.swing.JButton();
        signinbttn = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        txt_pwd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        txt_username1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(244, 223, 78));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/username.png"))); // NOI18N
        jLabel3.setText("Pasword");
        jLabel3.setIconTextGap(10);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 80, 30));

        signupbttn.setBackground(new java.awt.Color(244, 223, 78));
        signupbttn.setText("Sign Up");
        signupbttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        signupbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbttnActionPerformed(evt);
            }
        });
        jPanel2.add(signupbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 373, 240, 30));

        signinbttn.setBackground(new java.awt.Color(51, 204, 255));
        signinbttn.setText("Sign In");
        signinbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbttnActionPerformed(evt);
            }
        });
        jPanel2.add(signinbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 240, 30));

        txt_username.setForeground(new java.awt.Color(153, 153, 0));
        txt_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 240, 30));

        txt_pwd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        txt_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pwdActionPerformed(evt);
            }
        });
        jPanel2.add(txt_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 240, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Login");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 60, 40));

        txt_username1.setForeground(new java.awt.Color(153, 153, 0));
        txt_username1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        txt_username1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_username1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_username1FocusLost(evt);
            }
        });
        txt_username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_username1ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 240, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/username.png"))); // NOI18N
        jLabel6.setText("Username");
        jLabel6.setIconTextGap(10);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 420, 560));

        jPanel3.setBackground(new java.awt.Color(148, 147, 152));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin icon/taxi-librarian.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 280, 270));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 560));

        setSize(new java.awt.Dimension(835, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pwdActionPerformed

    private void signupbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbttnActionPerformed
        SignUp_Page signup=new SignUp_Page();
        signup.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signupbttnActionPerformed
    
    private void signinbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbttnActionPerformed
      if(loginValidation()){
          try {
              credValidation();
          } 
          catch (Exception ex) {
              ex.printStackTrace();
          }
      }
    }//GEN-LAST:event_signinbttnActionPerformed

    private void txt_username1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_username1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username1FocusGained

    private void txt_username1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_username1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username1FocusLost

    private void txt_username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username1ActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost

    }//GEN-LAST:event_txt_usernameFocusLost

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained

    }//GEN-LAST:event_txt_usernameFocusGained
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton signinbttn;
    private javax.swing.JButton signupbttn;
    private javax.swing.JPasswordField txt_pwd;
    private javax.swing.JTextField txt_username;
    private javax.swing.JTextField txt_username1;
    // End of variables declaration//GEN-END:variables
}
