/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Avilash
 */
public class ViewRecord extends javax.swing.JFrame {

    /**
     * Creates new form ViewRecord
     */
    DefaultTableModel tablemodel;

    public ViewRecord() {
        initComponents();
        setBookDetailsToTable();
    }

    //Setting Book details to table
    public void setBookDetailsToTable() {
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms", "root", "12345");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from issued_book");
            while (rs.next()) {
                String id = rs.getString("book_id");
                String studentName = rs.getString("student_name");
                String bookName = rs.getString("book_name");
                String issueDate = rs.getString("issue_date");
                String dueDate = rs.getString("due_date");
                String returnDate = rs.getString("return_date");
                String status = rs.getString("status");
                tablemodel = (DefaultTableModel) table_record.getModel();
                Object[] table_contents = {id, studentName, bookName, issueDate, dueDate, returnDate,status};
                /*
                Adds a row to the end of the model. The new row will contain null values unless rowData
                is specified. Notification of the row being added will be generated.
                 */
                tablemodel.addRow(table_contents);
                 System.out.println("set Book details");
            }

        } catch (Exception e) {

        }
    }

    private void clearTable() {
        DefaultTableModel model=(DefaultTableModel)table_record.getModel();
        model.setRowCount(0);
    }
    //search issued book details by date

    private void search() {
        //getDatoFecha(), Custom dateChoser componet method to fetch selected date and return java.util.Date type
        java.util.Date utilFromDate=dateC_fromDate.getDatoFecha();
        java.util.Date utilToDate=dateC_toDate.getDatoFecha();
        Long l1=utilFromDate.getTime();
        long l2=utilToDate.getTime();
        //But database supported date format is sql package date
        //Convert java.util.Date date format to java.sql.date format
        java.sql.Date sqlFromDate=new java.sql.Date(l1);
        java.sql.Date sqlToDate=new java.sql.Date(l2);
        try {
           
            Connection con = ConnectionProvider.createConnection();
            PreparedStatement pstm = con.prepareStatement("select * from issued_book where issue_date BETWEEN ? and ?");
            pstm.setDate(1, sqlFromDate);
            pstm.setDate(2, sqlToDate);
            ResultSet rs = pstm.executeQuery();
            
            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this, "Record not found");
            } 
            else {
                System.out.println("Inside else");
               
                while (rs.next()) {
                     System.out.println("Inside while");
                    String id = rs.getString("id");
                    String studentName = rs.getString("student_name");
                    String bookName = rs.getString("book_name");
                    String issueDate = rs.getString("issue_date");
                    String dueDate = rs.getString("due_date");
                    String returnDate = rs.getString("return_date");
                    String status = rs.getString("status");
                    tablemodel = (DefaultTableModel) table_record.getModel();
                    Object[] table_contents = {id, studentName, bookName, issueDate, dueDate,returnDate, status};
                    tablemodel.addRow(table_contents);
                   
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        label_bookDetails = new javax.swing.JLabel();
        dateC_toDate = new rojeru_san.componentes.RSDateChooser();
        jLabel12 = new javax.swing.JLabel();
        dateC_fromDate = new rojeru_san.componentes.RSDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_record = new rojerusan.RSTableMetro();
        bttn_allRecord = new javax.swing.JButton();
        bttn_search = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        label_exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main.setBackground(new java.awt.Color(54, 60, 73));
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_bookDetails.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_bookDetails.setForeground(new java.awt.Color(106, 110, 127));
        label_bookDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-list-view-60.png"))); // NOI18N
        label_bookDetails.setText("View Record");
        panel_main.add(label_bookDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 220, -1));

        dateC_toDate.setBackground(new java.awt.Color(102, 102, 102));
        dateC_toDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 60, 73)));
        dateC_toDate.setColorBackground(new java.awt.Color(40, 45, 55));
        dateC_toDate.setColorForeground(new java.awt.Color(0, 0, 0));
        dateC_toDate.setColorSelForeground(new java.awt.Color(204, 204, 204));
        dateC_toDate.setColorTextDiaActual(new java.awt.Color(153, 153, 153));
        dateC_toDate.setFuente(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dateC_toDate.setPlaceholder("Select a date");
        panel_main.add(dateC_toDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 300, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(106, 110, 127));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageStudentIcon/icons8-branching-arrows-20.png"))); // NOI18N
        jLabel12.setText("To Date");
        panel_main.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 90, 30));

        dateC_fromDate.setBackground(new java.awt.Color(102, 102, 102));
        dateC_fromDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 60, 73)));
        dateC_fromDate.setColorBackground(new java.awt.Color(40, 45, 55));
        dateC_fromDate.setColorForeground(new java.awt.Color(0, 0, 0));
        dateC_fromDate.setColorSelForeground(new java.awt.Color(204, 204, 204));
        dateC_fromDate.setColorTextDiaActual(new java.awt.Color(153, 153, 153));
        dateC_fromDate.setFuente(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dateC_fromDate.setPlaceholder("Select a date");
        panel_main.add(dateC_fromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 300, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(106, 110, 127));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManageStudentIcon/icons8-course-20.png"))); // NOI18N
        jLabel11.setText("From Date");
        panel_main.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 100, 30));

        table_record.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Student Name ", "Book Name", "Issue Date", "Due Date", "Return Date", "Status"
            }
        ));
        table_record.setColorBackgoundHead(new java.awt.Color(40, 45, 55));
        table_record.setColorBordeFilas(new java.awt.Color(54, 60, 73));
        table_record.setColorBordeHead(new java.awt.Color(54, 60, 73));
        table_record.setColorFilasBackgound1(new java.awt.Color(40, 45, 55));
        table_record.setColorFilasBackgound2(new java.awt.Color(40, 45, 55));
        table_record.setColorForegroundHead(new java.awt.Color(106, 110, 127));
        table_record.setRowHeight(62);
        table_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_recordMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_record);

        panel_main.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 1040, 420));

        bttn_allRecord.setBackground(new java.awt.Color(40, 45, 55));
        bttn_allRecord.setForeground(new java.awt.Color(106, 110, 127));
        bttn_allRecord.setText("All Record");
        bttn_allRecord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 110, 127)));
        bttn_allRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_allRecordActionPerformed(evt);
            }
        });
        panel_main.add(bttn_allRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 150, 110, 30));

        bttn_search.setBackground(new java.awt.Color(40, 45, 55));
        bttn_search.setForeground(new java.awt.Color(106, 110, 127));
        bttn_search.setText("Search");
        bttn_search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 110, 127)));
        bttn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_searchActionPerformed(evt);
            }
        });
        panel_main.add(bttn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 110, 110, 30));

        jLabel13.setBackground(new java.awt.Color(40, 45, 55));
        jLabel13.setForeground(new java.awt.Color(106, 110, 127));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Back");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(106, 110, 127)));
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        panel_main.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 110, 30));

        label_exit.setBackground(new java.awt.Color(54, 60, 73));
        label_exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        label_exit.setForeground(new java.awt.Color(255, 255, 255));
        label_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_exit.setText("X");
        label_exit.setOpaque(true);
        label_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_exitMouseExited(evt);
            }
        });
        panel_main.add(label_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, 50, 30));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 700));

        setSize(new java.awt.Dimension(1338, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_recordMouseClicked

    }//GEN-LAST:event_table_recordMouseClicked

    private void bttn_allRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_allRecordActionPerformed
        clearTable();
        setBookDetailsToTable();
    }//GEN-LAST:event_bttn_allRecordActionPerformed

    private void bttn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_searchActionPerformed
        if(dateC_fromDate.getDatoFecha() != null && dateC_toDate.getDatoFecha() != null){
                clearTable();
        search();
        }
        else{
            JOptionPane.showMessageDialog(this, "Select a date");
        }
    }//GEN-LAST:event_bttn_searchActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        HomePage home=new HomePage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void label_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_label_exitMouseClicked

    private void label_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseEntered
        label_exit.setBackground(Color.red);
    }//GEN-LAST:event_label_exitMouseEntered

    private void label_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_exitMouseExited
        label_exit.setBackground(new Color(54,60,73));
    }//GEN-LAST:event_label_exitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_allRecord;
    private javax.swing.JButton bttn_search;
    private rojeru_san.componentes.RSDateChooser dateC_fromDate;
    private rojeru_san.componentes.RSDateChooser dateC_toDate;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_bookDetails;
    private javax.swing.JLabel label_exit;
    private javax.swing.JPanel panel_main;
    private rojerusan.RSTableMetro table_record;
    // End of variables declaration//GEN-END:variables
}
